[default_session]
startup_command = "nvim"

[[session]]
name = "nvim config"
path = "~/dotfiles/.config/nvim/"
startup_command = "nvim -c :Neotree"

[[session]]
name = "tmux config"
path = "~/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "zsh config"
path = "~/dotfiles"
startup_command = "nvim .zshrc"


[[session]]
name = "kitty config"
path = "~/dotfiles/.config/kitty/"
startup_command = "nvim kitty.conf"

[[session]]
name = "sesh config"
path = "~/dotfiles/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
disable_startup_command = true

[[session]]
name = 'Projects'
path = '~/Projects'
disable_startup_command = true

[[session]]
name = "alacrety config"
path = "~/dotfiles/.config/alacritty/"
startup_command = "nvim alacritty.toml"
